//#define DEBUGPERF
using MPTK.NAudio.Midi;
using System.Collections.Generic;
using UnityEngine;

namespace MidiPlayerTK
{
    /// @ingroup midistreamplayer_management
    /// <summary>
    /// Builds and plays real-time music in response to user actions or algorithmic logic.
    /// This class is intended to be used with the MidiStreamPlayer prefab.
    /// 
    /// @attention 
    ///     - MidiStreamPlayer inherits from MidiSynth. For clarity, only MidiStreamPlayer-specific members are documented here.
    ///       See MidiSynth for the full list of inherited members.
    ///       
    /// No MIDI file is required. Notes are generated by your scripts with this class API.
    /// The main method, MPTK_PlayEvent(), together with MPTKEvent, allows you to create MIDI events such as note-on.
    /// Set all relevant values in MPTKEvent (command, note value, duration, and so on). See MPTKEvent for details.
    ///
    /// A note-on must eventually be stopped. For example, if duration = -1, the note is infinite
    /// and must be stopped with MPTK_StopEvent() (which sends a note-off).
    /// In Maestro Pro, chord playback is also available with MPTK_PlayChordFromRange() and MPTK_PlayChordFromLib().
    /// For scale playback, see MPTKRangeLib.
    /// For more information, see https://paxstellar.fr/midi-file-player-detailed-view-2-2/
    /// and the TestMidiStream demo source (TestMidiStream.cs).
    ///
    /// Because this class inherits from MidiSynth, all MidiSynth properties, events,
    /// and methods are also available here.
    ///
    /// @note
    ///     - A full example is provided below.
    ///     - You cannot copy and paste this extract directly, but the complete source code
    ///       is available with Maestro MPTK Free.
    ///     - Some features are available only with the Pro version.
    /// @snippet TestMidiStream.cs ExampleFullMidiStream
    /// </summary>
    //[RequireComponent(typeof(MidiPlayerGlobal))] -- not possible.It's a singleton object, all gameobjects will be merge at run time
    [RequireComponent(typeof(AudioSource))]
    [RequireComponent(typeof(AudioReverbFilter))]
    [RequireComponent(typeof(AudioChorusFilter))]
    [HelpURL("https://paxstellar.fr/midi-file-player-detailed-view-2-2/")]
    public partial class MidiStreamPlayer : MidiSynth
    {
        /// <summary>
        /// Description and list of MIDI channels associated with the synth.
        /// Each MIDI synth has 16 channels that carry all the relevant MIDI information.
        ///     - Current instrument / bank
        ///     - Volume
        ///     - Mute / Unmute (see Enable)
        ///     - Pitch bend ...
        ///     
        /// Channels distinguish instruments and provide independent control for each one.
        /// By sending MIDI messages on each channel, you can change instrument, volume, pitch, and other parameters.
        /// In Maestro MPTK, channels are indexed from 0 to 15. Channel 9 is reserved for drum sounds.
        /// 
        /// @snippet TestMidiFilePlayerScripting.cs ExampleUsingChannelAPI_Full
        /// </summary>
        /// @ingroup midistreamplayer_channels
        public MPTKChannels MPTK_Channels
        {
            get { return Channels; }
        }

        new void Awake()
        {
            base.Awake();
        }

        new void Start()
        {
            MPTK_StartMidiStream();
        }

        // removed V2.89.0
        //private bool startIsDone = false;

        /// <summary>@brief
        /// Forces initialization of MidiStreamPlayer.
        /// Useful when another component needs to send MIDI commands as soon as the application starts.
        /// @code
        /// 
        /// // Find a MidiStreamPlayer Prefab from the scene
        /// MidiStreamPlayer MidiStream = FindFirstObjectByType<MidiStreamPlayer>();
        /// MidiStream.MPTK_StartMidiStream();
        ///
        /// @endcode        
        /// </summary>
        /// @ingroup midistreamplayer_events
        public void MPTK_StartMidiStream()
        {
            //Debug.Log($"*** MPTK_StartMidiStream IdSynth:{IdSynth} ***");
            //if (!startIsDone)
            {
                //startIsDone = true;
                try
                {
                    MPTK_InitSynth();
                    // With v2.10.1 the choice is available in the inspector. True by default.
                    // MPTK_EnablePresetDrum = true;
                    base.Start();
                    // V2.88.2 forced EnablePresetDrum to true removed -  Always enabled for midi stream or need to be change by script
                    //MPTK_EnablePresetDrum = true;
                    ThreadDestroyAllVoice();
                }
                catch (System.Exception ex)
                {
                    MidiPlayerGlobal.ErrorDetail(ex);
                }
            }
        }

        /// <summary>@brief
        /// Plays one MIDI event from an instance of MPTKEvent.
        /// Runs in a thread so the call returns immediately.
        /// See also the method #MPTK_StopEvent to stop a note from an instance of MPTKEvent.
        /// @snippet MusicView.cs Example PlayNote
        /// </summary>
        /// @ingroup midistreamplayer_events
        /// <param name="mptkEvent">Instance of MPTKEvent to play.</param>
        public void MPTK_PlayEvent(MPTKEvent mptkEvent)
        {
            try
            {
                if (MPTK_SoundFont.IsReady)
                {
                    if (!MPTK_CorePlayer)
                        Routine.RunCoroutine(TheadPlay(mptkEvent), Segment.RealtimeUpdate);
                    else
                    {
                        lock (this) // V2.83
                        {
                            QueueSynthCommand.Enqueue(new SynthCommand() { Command = SynthCommand.enCmd.StartEvent, MidiEvent = mptkEvent });
                        }
                    }
                }
                else
                    Debug.LogWarning($"SoundFont not yet loaded, MIDI Event cannot be processed Code:{mptkEvent.Command} Channel:{mptkEvent.Channel}");
            }
            catch (System.Exception ex)
            {
                MidiPlayerGlobal.ErrorDetail(ex);
            }
        }

        /// <summary>@brief
        /// Plays a list of MIDI events from MPTKEvent instances.
        /// Runs in a thread so the call returns immediately.
        /// See also the method #MPTK_StopEvent to stop a note from an instance of MPTKEvent.
        /// @snippet TestMidiStream.cs ExampleMPTK_PlayEvent
        /// </summary>
        /// @ingroup midistreamplayer_events
        /// <param name="mptkEvents">List of MPTKEvent instances to play.</param>
        public void MPTK_PlayEvent(List<MPTKEvent> mptkEvents)
        {
            try
            {
                if (MPTK_SoundFont.IsReady)
                {
                    if (!MPTK_CorePlayer)
                        Routine.RunCoroutine(TheadPlay(mptkEvents), Segment.RealtimeUpdate);
                    else
                    {
                        lock (this) // V2.83
                        {
                            foreach (MPTKEvent evnt in mptkEvents)
                                QueueSynthCommand.Enqueue(new SynthCommand() { Command = SynthCommand.enCmd.StartEvent, MidiEvent = evnt });
                        }
                    }
                }
                else
                    Debug.LogWarning($"SoundFont not yet loaded");
            }
            catch (System.Exception ex)
            {
                MidiPlayerGlobal.ErrorDetail(ex);
            }
        }

        private IEnumerator<float> TheadPlay(MPTKEvent evnt)
        {
            if (evnt != null)
            {
                try
                {
                    //TBR if (!MPTK_PauseOnDistance || MidiPlayerGlobal.MPTK_DistanceToListener(this.transform) <= VoiceTemplate.Audiosource.maxDistance)
                    {
#if DEBUGPERF
                        DebugPerf("-----> Init perf:", 0);
#endif
                        MPTK_PlayDirectEvent(evnt);
#if DEBUGPERF
                        DebugPerf("<---- ClosePerf perf:", 2);
#endif
                    }
                }
                catch (System.Exception ex)
                {
                    MidiPlayerGlobal.ErrorDetail(ex);
                }
            }
            yield return 0;
        }

        private IEnumerator<float> TheadPlay(List<MPTKEvent> events)
        {
            if (events != null && events.Count > 0)
            {
                try
                {
                    try
                    {
                        //TBR if (!MPTK_PauseOnDistance || MidiPlayerGlobal.MPTK_DistanceToListener(this.transform) <= VoiceTemplate.Audiosource.maxDistance)
                        {
                            PlayEvents(events, true);
                        }
                    }
                    catch (System.Exception ex)
                    {
                        MidiPlayerGlobal.ErrorDetail(ex);
                    }
                }
                catch (System.Exception ex)
                {
                    MidiPlayerGlobal.ErrorDetail(ex);
                }
            }
            yield return 0;

        }

        /// <summary>@brief
        /// Stops a currently playing note. All samples associated with the note are stopped by sending a note-off.
        /// The parameter must be an MPTKEvent instance previously used with MPTK_PlayEvent.
        /// @code
        /// void Update()
        /// {
        ///     if (Input.GetKeyDown(KeyCode.Space))
        ///     {
        ///        // Assign our "Hello, World!"-equivalent note (using MPTKEvent's defaults plus Value = 60 for C5.
        ///        // HelperNoteLabel class could be your friend)
        ///        mptkEvent = new MPTKEvent() { Value = 60 };
        ///        // Start playing our "Hello, World!"-equivalent note
        ///        midiStreamPlayer.MPTK_PlayEvent(mptkEvent);
        ///    }
        ///    else if (Input.GetKeyUp(KeyCode.Space))
        ///    {
        ///        // Stop playing our "Hello, World!"-equivalent note
        ///        midiStreamPlayer.MPTK_StopEvent(mptkEvent);
        ///    }
        /// }
        /// @endcode
        /// </summary>
        /// @ingroup midistreamplayer_events
        /// <param name="mptkEvent">MPTKEvent instance used to start the note with MPTK_PlayEvent.</param>
        public void MPTK_StopEvent(MPTKEvent mptkEvent)
        {
            if (!MPTK_CorePlayer)
                StopEvent(mptkEvent);
            else
            {
                lock (this) // V2.83
                {
                    QueueSynthCommand.Enqueue(new SynthCommand() { Command = SynthCommand.enCmd.StopEvent, MidiEvent = mptkEvent });
                }
            }
        }
    }
}

